name: Test sur runner auto-hébergé

on:
  push:
    branches:
      - main

jobs:
  test:
    name: ci-cd on self hosted runner
    runs-on: self-hosted

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Linter
        run: |
          pylint ./ | tee rapport_pylint.txt
      
      - name: Run test
        run: |
          pytest ./test.py
    
    steps:

      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Build image docker
        run: |
          docker build -t tp-docker:latest .
      
      - name: Docker compose
        run: |
          docker compose pull
          docker compose up -d
      
      - name:
        run: |
          docker ps

    
