name: Test sur runner auto-hébergé

on:
  push:
    branches:
      - master

jobs:
  test:
    name: ci-cd on self hosted runner
    runs-on: self-hosted

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Linter
        run: |
          source venv/bin/activate
          pylint --ignore=venv . | tee rapport_pylint.txt
      
      - name: Run test
        run: |
          source venv/bin/activate
          pytest ./test.py

      - name: Build image docker
        run: |
          sudo docker build -t tp-docker .
          sudo docker tag titouanbonnetplomb/tp-docker:latest
      
      - name: Docker compose
        run: |
          sudo docker compose pull
          sudo docker compose up -d
      
      - name: check docker
        run: |
          sudo docker ps

    
